Fix console scalacOptions
The scala repl isn't usable,

    sbt> jvm/console
    [info] Starting scala interpreter...

    scala> import org.scalacheck.Prop
    import org.scalacheck.Prop
    <console>:11: warning: Unused import
           import org.scalacheck.Prop
                                 ^
    error: No warnings can be incurred under -Xfatal-warnings.

    scala> Prop.passed
    <console>:12: error: not found: value Prop
           Prop.passed
           ^

The unused-import fatal warning for the console used to be disabled,
but the filter of it was dismantled when an alternate version of
the compiler flag, -Ywarn-unused-import, was introduced in 772ee614.